### ISSUE TITLE
Problem with response()->download($path)

### ISSUE THREAD

**Issue by mezhevikin** [nckg/laravel-minify-html#2]
Hello!
Thank you for the lib.
I have problem with **return response()->download($path)**.
How to disable MinifyResponse for this case?

Error:

```
The content cannot be set on a BinaryFileResponse instance.  (LogicException(code: 0): The content cannot be set on a BinaryFileResponse instance. at /var/www/examenpdd/vendor/symfony/http-foundation/BinaryFileResponse.php:323)
[stacktrace]
#0 /var/www/examenpdd/vendor/nckg/laravel-minify-html/src/Middleware/MinifyResponse.php(25): Symfony\\Component\\HttpFoundation\\BinaryFileResponse->setContent('')
```

**Comment by nckg** [comment]
You can overwrite the middleware class with your own for now.
That way you can check if the response is a `BinaryFileResponse`.

I'll create a fix that will check for the `BinaryFileResponse`
